apiVersion: v1
kind: PersistentVolume
metadata:
  name: sql-persistentvolume
  labels:
    sql: sql-server
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /sql-server
    type: DirectoryOrCreate