FROM eclipse-temurin:17.0.9_9-jre-jammy

MAINTAINER "Jawahar"

WORKDIR /azure-demo

COPY target/demo-0.0.1-SNAPSHOT.jar .

EXPOSE $PORT
ENV AZURE_STORAGE dummy_storage
ENV AZURE_STORAGE_ACCOUNT_NAME dummy_acct_name
ENV AZURE_STORAGE_SUBSCRIPTION_ID dummy_subs_id
ENV AZURE_STORAGE_RESOURCE_GROUP dummy_rg
ENV AZURE_STORAGE_CONNECTION_STRING dummy_connect_string
ENV AZURE_STORAGE_ACCOUNT_KEY dummy_sg_key
ENV AZURE_STORAGE_QUEUE_NAME dummy_queue_name
ENV DB_USERNAME dummy_user
ENV DB_PASSWORD dummy_password
ENV JDBC_URL dummy_url
ENV AZURE_STORAGE_CONTAINER_NAME dummy_cont_name
ENV AZURE_STORAGE_CONTAINER_FILE_NAME dummy.txt

ENTRYPOINT ["java", "-jar", "demo-0.0.1-SNAPSHOT.jar"]