apiVersion: v1
kind: Service
metadata:
  name: sql-service
  labels:
    sql: sql-server
spec:
  selector:
    sql: sql-server
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 1433
      targetPort: 1433
